#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Python version: 3.7

import argparse
def args_parser():
    parser = argparse.ArgumentParser()

    # federated arguments (Notation for the arguments followed from paper)
    parser.add_argument('--epochs', type=int, default=20,
                        help="number of rounds of training")
    parser.add_argument('--num_users', type=int, default=16,
                        help="number of users: K")
    parser.add_argument('--client_selection_num', type=int, default=16,
                        help='The number of selected clients.')
    parser.add_argument('--local_ep', type=int, default=50,
                        help="the number of local epochs: E")
    parser.add_argument('--local_bs', type=int, default=128,
                        help="local batch size: B")
    parser.add_argument('--is_aggregate_with_weights', type=int, default=0,
                        help="When aggregation, whether to use the client's sample as the weight.")
    parser.add_argument('--lr', type=float, default=0.1,
                        help='learning rate')
    parser.add_argument('--optimizer', type=str, default='sgd', help="type \
                        of optimizer")
    parser.add_argument('--momentum', type=float, default=0.9,
                        help='SGD momentum (default: 0.9)')
    parser.add_argument('--stopping_rounds', type=int, default=20,
                        help='rounds of early stopping')


    # model arguments
    parser.add_argument('--model', type=str, default='resnet18', help='test, restnet18, shufflenetv2')
    parser.add_argument('--save_local', type=int, default=0, help='save local models or not')
    parser.add_argument('--save_global', type=int, default=1, help='save global models or not')

    
    # other arguments
    parser.add_argument('--dataset', type=str, default='MNIST', 
                        help="name of dataset. ['cifar10','cifar100','MNIST']")
    parser.add_argument('--iid', type=int, default=0,
                        help='Default set to IID. Set to 0 for non-IID.')
    # parser.add_argument('--comparing_shared', type=int, default=0, help='comparing shared or not')
    parser.add_argument('--shared_data', type=float, default=0, help='using shared data or not')
    parser.add_argument('--partition', type=str, default='hetero-dir', help='homo, hetero-dir ')
    parser.add_argument('--compare_sever_client_masks', type=int, default=1, help='Whether to compare the mask generated by global and local during XAI evaluation.')
    
    parser.add_argument('--XAI_evaluate_batch_size', type=int, default=16,help="During the XAI_evaluate process, the number of samples to be calculated at one time.")
    parser.add_argument('--XAI_evaluate_nt_samples', type=int, default=5,help="During the XAI_evaluate process, the number of interpretable algorithm samples.")
    parser.add_argument('--XAI_evaluate_n_steps', type=int, default=5,help="In the XAI_evaluate process, the number of a sample step.")
    parser.add_argument('--mode', type=int, default=6,
                        help='[0,2,4,5]。0 means FedAvg, randomly select the client; \
                                    2 means that only the mask is used in the test, and then the client is screened by acc, and the mask will be generated by the server model and testing dataset before the test;\
                                    4 means fedProx; \
                                    5 indicates that the optimal client (oort\') is selected based on the task acc as a reference standard；')
    
   
    #mode == 2
    parser.add_argument('--mode2_end_epoch', type=int, default=5,help="Mode 2 needs to be discontinued after a few rounds.")
    parser.add_argument('--test_mask_batch_size', type=int, default=2000,help="Generate a test set mask, the number of masks calculated at one time.")
    parser.add_argument('--test_mask_nt_samples', type=int, default=1,help="IG algorithm, the number of times a sample is sampled.")
    parser.add_argument('--test_mask_n_steps', type=int, default=1,help="IG algorithm, a sample step number.")
     
     
    
    #mode == 3 4  
    parser.add_argument('--mse_loss_lambda', type=float, default=0.01,help="")
    parser.add_argument('--mapping', type=int, default=0,help="")
    parser.add_argument('--topk', type=float, default=0.3,help="After counting the ratio of the artificially labeled mask to the total pixels of the original image, it is recommended that MNIST use 0.1.")
    parser.add_argument('--verbose', type=int, default=1, help='verbose')
    
    parser.add_argument('--random_seed', type=int, default=40212202)
    parser.add_argument('--gpu', default=0, type=int, help="To use cuda, set \
                        to a specific GPU ID. Default set to use CPU.")

    args = parser.parse_args()
    return args
